FROM rustlang/rust:nightly-slim AS builder

WORKDIR /home/rust/solana/
RUN apt-get update && apt-get install -y libssl-dev pkg-config wget bzip2
RUN wget https://github.com/solana-labs/solana/releases/download/v1.18.15/solana-release-x86_64-unknown-linux-gnu.tar.bz2
RUN tar jxf solana-release-x86_64-unknown-linux-gnu.tar.bz2
ENV PATH=/home/rust/solana/solana-release/bin:$PATH

WORKDIR /testnet
COPY ./accounts ./accounts
COPY ./deploy.sh ./deploy.sh
RUN chmod +x ./deploy.sh

CMD [ "sh", "./deploy.sh" ]
